"""A2A Agent Cards — describes each agent's capabilities per Google A2A spec."""

AGENT_CARDS = {
    "requirements": {
        "name": "requirements",
        "description": "Product Manager agent. Writes PRD specs, user stories, and acceptance criteria from a task description.",
        "capabilities": ["requirements_gathering", "prd_writing", "user_stories"],
        "input_schema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]},
        "output_schema": {"type": "object", "properties": {"result": {"type": "string"}}},
        "tags": ["planning", "product"],
    },
    "architect": {
        "name": "architect",
        "description": "Tech Lead agent. Designs system architecture, file structure, and component boundaries.",
        "capabilities": ["system_design", "file_planning", "architecture_decisions"],
        "input_schema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]},
        "output_schema": {"type": "object", "properties": {"result": {"type": "string"}}},
        "tags": ["architecture", "design"],
    },
    "coder": {
        "name": "coder",
        "description": "Senior Full-Stack Developer agent. Writes production code given a spec and architecture plan.",
        "capabilities": ["code_generation", "bug_fixing", "refactoring"],
        "input_schema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]},
        "output_schema": {"type": "object", "properties": {"result": {"type": "string"}}},
        "tags": ["coding", "development"],
    },
    "reviewer": {
        "name": "reviewer",
        "description": "Code Reviewer agent. Reviews code for bugs, security issues, and style violations.",
        "capabilities": ["code_review", "bug_detection", "security_check"],
        "input_schema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]},
        "output_schema": {"type": "object", "properties": {"result": {"type": "string"}}},
        "tags": ["review", "quality"],
    },
    "tester": {
        "name": "tester",
        "description": "QA Engineer agent. Writes and runs tests, identifies coverage gaps.",
        "capabilities": ["test_generation", "test_execution", "coverage_analysis"],
        "input_schema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]},
        "output_schema": {"type": "object", "properties": {"result": {"type": "string"}}},
        "tags": ["testing", "qa"],
    },
    "security": {
        "name": "security",
        "description": "Security Engineer agent. Performs OWASP Top 10 audits and identifies vulnerabilities.",
        "capabilities": ["security_audit", "vulnerability_detection", "owasp_review"],
        "input_schema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]},
        "output_schema": {"type": "object", "properties": {"result": {"type": "string"}}},
        "tags": ["security", "owasp"],
    },
    "debugger": {
        "name": "debugger",
        "description": "Debugger agent. Diagnoses and fixes runtime errors and test failures.",
        "capabilities": ["debugging", "error_diagnosis", "fix_generation"],
        "input_schema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]},
        "output_schema": {"type": "object", "properties": {"result": {"type": "string"}}},
        "tags": ["debugging", "fixes"],
    },
    "docs": {
        "name": "docs",
        "description": "Technical Writer agent. Generates README files, API docs, and inline documentation.",
        "capabilities": ["documentation", "readme_generation", "api_docs"],
        "input_schema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]},
        "output_schema": {"type": "object", "properties": {"result": {"type": "string"}}},
        "tags": ["documentation", "writing"],
    },
    "planner": {
        "name": "planner",
        "description": "Planner agent. Breaks down tasks into ordered implementation steps.",
        "capabilities": ["task_planning", "step_decomposition", "dependency_mapping"],
        "input_schema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]},
        "output_schema": {"type": "object", "properties": {"result": {"type": "string"}}},
        "tags": ["planning", "decomposition"],
    },
    "evaluator": {
        "name": "evaluator",
        "description": "Engineering Manager agent. Makes ship/no-ship decisions based on review, test, and security outputs.",
        "capabilities": ["quality_evaluation", "ship_decision", "feedback_synthesis"],
        "input_schema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]},
        "output_schema": {"type": "object", "properties": {"result": {"type": "string"}}},
        "tags": ["evaluation", "management"],
    },
}
